version: "3.9"
services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: app-api
    environment:
      - PORT=4000
      - CORS_ORIGIN=http://localhost:3000
      - DATABASE_URL=file:/data/dev.db
      - JWT_ACCESS_SECRET=dev_access_secret
    volumes:
      - api_data:/data
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4000/"]
      interval: 10s
      timeout: 3s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-web
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      api:
        condition: service_healthy

volumes:
  api_data:

