import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <nav className="bg-gray-900 text-white p-4 flex gap-4">
          <Link href="/">Home</Link>
          <Link href="/dashboard">Dashboard</Link>
        </nav>
        <main className="min-h-screen">{children}</main>
        {/* <footer className="bg-gray-100 text-center py-4 mt-6">
          <p className="text-sm text-gray-600">© 2025 My App</p>
        </footer> */}
      </body>
    </html>
  );
}
